---

- name: "tumbumer.sshd: fail if the os version does not match"
  fail:
    msg: "OS must be Ubuntu 18.04 Bionic Beaver"
  when: not (ansible_distribution == "Ubuntu" and ansible_distribution_release == "bionic")

- name: "tumbumer.sshd: check that openssh-server is installed"
  command: "dpkg-query -s openssh-server"
  register: tumbumer_sshd_check
  failed_when: tumbumer_sshd_check.rc != 0
  changed_when: false

- name: "tumbumer.sshd: update /etc/ssh/sshd_config"
  become: yes
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  when: tumbumer_sshd_update_config == true
  notify:
    - tumbumer-sshd-restart

- name: "tumbumer.sshd: delete remote host keyfiles"
  become: yes
  shell: /bin/rm -f /etc/ssh/ssh_host_*
  args:
    warn: false
  when: (tumbumer_sshd_host_key_action == "create" or tumbumer_sshd_host_key_action == "update")
  notify:
    - tumbumer-sshd-restart

- name: "tumbumer.sshd: create remote host keyfiles"
  become: yes
  openssh_keypair:
    path: /etc/ssh/ssh_host_ed25519_key
    type: ed25519
    comment: "{{ ansible_fqdn }}"
  when: tumbumer_sshd_host_key_action == "create"
  notify:
    - tumbumer-sshd-restart

- name: "tumbumer.sshd: get ssh host keys from vault"
  local_action:
    module: set_fact
    tumbumer_sshd_private_key: "{{ lookup('hashi_vault', 'auth_method=approle url={{ tumbumer_sshd_vault_url }} role_id={{ tumbumer_sshd_vault_role_id }} secret_id={{ tumbumer_sshd_vault_secret_id }} secret={{ tumbumer_sshd_vault_private_key }}') }}"
    tumbumer_sshd_public_key: "{{ lookup('hashi_vault', 'auth_method=approle url={{ tumbumer_sshd_vault_url }} role_id={{ tumbumer_sshd_vault_role_id }} secret_id={{ tumbumer_sshd_vault_secret_id }} secret={{ tumbumer_sshd_vault_public_key }}') }}"
  register: tumbumer_sshd_keys
  when: tumbumer_sshd_host_key_action == "update"

- name: "tumbumer.sshd: push remote host private keyfile"
  become: yes
  copy:
    content: "{{ tumbumer_sshd_private_key }}"
    dest: /etc/ssh/ssh_host_ecdsa_key
    owner: root
    group: root
    mode: 0600
  when: tumbumer_sshd_host_key_action == "update"
  notify:
    - tumbumer-sshd-restart

- name: "tumbumer.sshd: push remote host public keyfile"
  become: yes
  copy:
    content: "{{ tumbumer_sshd_public_key }}"
    dest: /etc/ssh/ssh_host_ecdsa_key.pub
    owner: root
    group: root
    mode: 0644
  when: tumbumer_sshd_host_key_action == "update"
  notify:
    - tumbumer-sshd-restart
