---
- name: "tumbumer.sshd: check that openssh-server is installed"
  command: "dpkg-query -s openssh-server"
  register: tumbumer_sshd_check
  failed_when: tumbumer_sshd_check.rc != 0
  changed_when: false

- name: "tumbumer.sshd: update /etc/ssh/sshd_config"
  become: yes
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  when: tumbumer_sshd_update_config
  notify:
    - tumbumer-sshd-restart

- name: "tumbumer.sshd: delete remote host keyfiles"
  become: yes
  shell: /bin/rm -f /etc/ssh/ssh_host_*
  args:
    warn: false
  when: (tumbumer_sshd_host_key_action == "create" or tumbumer_sshd_host_key_action == "update")
  notify:
    - tumbumer-sshd-restart

- name: "tumbumer.sshd: create remote host keyfiles"
  become: yes
  openssh_keypair:
    path: /etc/ssh/ssh_host_ed25519_key
    type: ed25519
    comment: "{{ ansible_fqdn }}"
  when: tumbumer_sshd_host_key_action == "create"
  notify:
    - tumbumer-sshd-restart

- name: "tumbumer.sshd: push remote host private keyfile"
  become: yes
  copy:
    content: "{{ tumbumer_sshd_private_key }}"
    dest: /etc/ssh/ssh_host_ed25519_key
    owner: root
    group: root
    mode: 0600
  when: tumbumer_sshd_host_key_action == "update"
  notify:
    - tumbumer-sshd-restart

- name: "tumbumer.sshd: push remote host public keyfile"
  become: yes
  copy:
    content: "{{ tumbumer_sshd_public_key }}"
    dest: /etc/ssh/ssh_host_ed25519_key.pub
    owner: root
    group: root
    mode: 0644
  when: tumbumer_sshd_host_key_action == "update"
  notify:
    - tumbumer-sshd-restart
